### ISSUE TITLE
overhaul features checklist

### ISSUE THREAD

**Issue by ExpandingMan** [ExpandingMan/Anamnesis.jl#2]
- [ ] Both more robust and more flexible file management.  Users should have the ability to name files easily but also forget about underlying file management if they want to.
- [ ] DataStreams integration and arbitrary output types for files.  Should completely drop DataFrames as a dependency.
- [ ] Both more robust and more flexible approximation schemes for memoizing numerical output.
- [ ] More flexibility in how function calls appear.  The MacroTools integration will solve this easily.
